services:
  PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory

  PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory

  PrestaShop\Module\PrestashopFacebook\Factory\ErrorHandlerFactoryInterface: '@PrestaShop\Module\PrestashopFacebook\Factory\ErrorHandlerFactory'

  PrestaShop\Module\PrestashopFacebook\Factory\ErrorHandlerFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\ErrorHandlerFactory
