services:
  PrestaShop\Module\PrestashopFacebook\Repository\GoogleCategoryRepository:
    class: PrestaShop\Module\PrestashopFacebook\Repository\GoogleCategoryRepository

  PrestaShop\Module\PrestashopFacebook\Repository\ProductRepository:
    class: PrestaShop\Module\PrestashopFacebook\Repository\ProductRepository

  PrestaShop\Module\PrestashopFacebook\Repository\TabRepository:
    class: PrestaShop\Module\PrestashopFacebook\Repository\TabRepository
